#!/usr/bin/env bash

# Symlink config files, overwriting and creating directories as needed.
#
# Execute with an argument to specify install type: ./install work|linux
# Otherwise it will default to base install.

run_setup() {
  local header="\n*** %s ***\n"
  local configs=~/Projects/configs

  if [[ $1 == m* ]] || [[ $1 == w* ]] ; then # "mac" or "work"
    local install_type='work'
    local work=1
  elif [[ $1 == l* ]] || [[ $1 == h* ]] ; then # "linux" or "home"
    local install_type='linux'
    local linux=1
  else
    install_type='base'
  fi

  echo "Running $install_type setup"

  printf "$header" "git"

  ln -fsv "$configs/git/.gitignore" ~
  ln -fsv "$configs/git/.gitconfig" ~
  ln -fsv "$configs/git/.gitk"      ~

  if [ ! -f ~/.git-completion.bash ]; then
    echo "Getting git-completion.bash"
    curl -o ~/.git-completion.bash \
      https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
  fi

  printf "$header" "shell/terminal"

  ln -fsv "$configs/terminal/.inputrc"            ~
  ln -fsv "$configs/terminal/.bash_profile"       ~
  if [ $work ] ; then
    ln -fsv "$configs/terminal/.bashrc-work"      ~/.bashrc
  elif [ $linux ] ; then
    mkdir -pv ~/.config/terminator
    ln -fsv "$configs/terminal/.bashrc-linux"     ~/.bashrc
    ln -fsv "$configs/terminal/terminator-config" ~/.config/terminator/config
  else
    ln -fsv "$configs/terminal/.bashrc-base"      ~/.bashrc
  fi

  if [ $linux ] ; then
    printf "$HEADER" "lint"
    ln -fsv "$configs/linters/.pylintrc" ~
    ln -fsv "$configs/linters/.eslintrc" ~
  fi

  printf "$header" "misc"

  ln -fsv "$configs/.agignore" ~

  printf "$header" "vim"

  ln -fsv "$configs/vim/.vimrc"  ~
  ln -fsv "$configs/vim/.gvimrc" ~

  if [ ! -f ~/.vim/autoload/plug.vim ] ; then
    echo "Downloading vim-plug"
    curl -Lo ~/.vim/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  mkdir -pv ~/.vim
  ln -fsv "$configs/vim/colors"              ~/.vim
  ln -fsv "$configs/vim/custom-after"        ~/.vim
  ln -fsv "$configs/vim/custom-snippets"     ~/.vim
  ln -fsv "$configs/vim/CustomGrepFileAssoc" ~/.vim
  ln -fsv "$configs/vim/filetype.vim"        ~/.vim

  echo -e "\n====> Make sure to run :PlugInstall once you open vim\n"
}

run_setup $1
